# cat docker-compose.yml
version: '3.5'
services:
  ### MySQL Container
  pia-db:
    image: pia-db
    container_name: pia-db
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: heslo
      MYSQL_DATABASE: piae_v1_db
      MYSQL_ROOT_PASSWORD: heslo
    ports:
      - "3306:3306"
    command: --skip-ssl
    build:
      dockerfile: mysql.dockerfile
#    volumes:
#      - eess-pg-data:/var/lib/postgresql/data
