package cz.zcu.kiv.mjakubas.piae.sem.webapplication;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * AUTOGENERATED
 */
@SpringBootApplication(scanBasePackages = "cz.zcu.kiv.mjakubas.piae")
public class SemApplication {

    public static void main(String[] args) {
        SpringApplication.run(SemApplication.class, args);
    }

}
